### ISSUE TITLE
Add Ubuntu Thin to the font download

### ISSUE THREAD

**Issue by spencerbygraves** [canonical-web-and-design/design.ubuntu.com#107]
## Summary

Add Ubuntu Thin to the font download

## Process

At the bottom of the page here - https://design.ubuntu.com/font/

## Asset

[Ubuntu-Th.ttf](https://www.dropbox.com/sh/kryvdt2w1y5n7n9/AACTrFnOBtZ9TIPf7vIKcT-ca?dl=0)

**Comment by SirSamTumless** [comment]
Issue moved to [canonical-web-and-design/web-squad #1141](https://github.com/canonical-web-and-design/web-squad/issues/1141) via [**ZenHub**](https://www.zenhub.com/)
