### ISSUE TITLE
Dead link to Ubuntu Font Licence

### ISSUE THREAD

**Issue by fitojb** [canonical-web-and-design/design.ubuntu.com#158]
## Summary

1. Go to https://fonts.google.com/specimen/Ubuntu#license
2. Click the [link](http://font.ubuntu.com/ufl/) provided there to read the Ubuntu Font Licence
3. Stumble in a [404](https://design.ubuntu.com/font/ufl) page.

The initial redirect should go to https://ubuntu.com/legal/font-licence instead of its current place.

**Comment by tbille** [comment]
This is done and live. Thanks for opening this issue!
