### ISSUE TITLE
Wrong wordwrap

### ISSUE THREAD

**Issue by EnergoKoder** [canonical-web-and-design/design.ubuntu.com#195]
## Summary

Your articles indicate, that you pay great attention to look and feel your web sites. That is right. But wrong is fixed web page width. This case your sites are unreadable on my 13" laptop screen. So please make correct sites without silly asumptions.

## Process
Install Kubuntu on laptop with 13" screen;
Install QuiteRss;
Add https://planet.ubuntu.com/rss20.xml rss chanell.
Open https://ubuntu.com//blog/announcing-ubuntu-on-windows-community-preview-wsl-2 article.
Then you will see something like on screenshot bellow.

## Current and expected result

I see only small part of the page.
I expect page will fill available screen width and long lines will be wordwraped nicelly.
For example correct page is: http://losca.blogspot.com/2021/03/motionphoto-microvideo-file-formats-on.html

## Screenshot
![obraz](https://user-images.githubusercontent.com/63141901/113183259-561ae780-9243-11eb-950b-1eb174d55ce3.png)

**Comment by pmahnke** [comment]
@EnergoKoder thanks for filing this... and I completely agree.

Planet isn't really maintained by the web team and there are existing issues against that project to get this fixed, so I am going to close this here.
