### ISSUE TITLE
Pictograms are not available via the brand downloads page

### ISSUE THREAD

**Issue by diddledani** [canonical-web-and-design/design.ubuntu.com#210]
## Summary

Pictograms are not available via the brand downloads page

## Process

1. Go to https://design.ubuntu.com/downloads/
2. Try to find the Ubuntu pictograms on the page to download them
3. Find they're not listed as a downloadable file
3. ...
4. profit?

## Current and expected result

The pictograms are unavailable from any current source.

We need to restore access to these pictograms.

**Comment by sowasred2012** [comment]
@diddledani thanks for filing an issue - what pictograms are you looking for?

**Comment by diddledani** [comment]
Hiya, I was looking for the collection mentioned at https://design.ubuntu.com/brand/pictograms/

**Comment by waynecrosby** [comment]
@diddledani Unfortunately the pictograms are no longer used by ourselves internally or externally and as such are not available for download anymore. We will remove that section from https://design.ubuntu.com/brand/pictograms/ to avoid any future confusion. Thanks for your interest and hope this doesn't cause you any problems.

**Comment by sowasred2012** [comment]
Closing this issue, the section will be removed: https://github.com/canonical-web-and-design/design.ubuntu.com/issues/211
