### ISSUE TITLE
HTML coverage maps

### ISSUE THREAD

**Issue by deadlight** [canonical-web-and-design/design.ubuntu.com#76]
## Summary

Fontaine is a tool that can produce HTML coverage maps for fonts. Ideally this could be integrated to give a good vision status indication of completeness:

Note that first fontaine will need .deb packaging: bug #673952

As of 2016, it lives in Github:

  [https://github.com/davelab6/pyfontaine](https://github.com/davelab6/pyfontaine
)

with a webpage overview at:

  [https://pypi.python.org/pypi/fontaine/1.1.5](https://pypi.python.org/pypi/fontaine/1.1.5)

and can be installed with Python pip:

  `pip install fontaine`

**Comment by davelab6** [comment]
LMK if you have any questions; pyfontaine provides all the public language databases I'm aware of, but doesn't today provide a 'single best' dataset.

**Comment by SirSamTumless** [comment]
Closed in 19.04. Please reopen as required.
